import {
  Activity,
  Ambulance,
  Armchair,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Backpack,
  Baby,
  BadgeCheck,
  BadgeEuro,
  BadgeInfo,
  BadgePercent,
  Ban,
  BanknoteArrowDown,
  BanknoteArrowUp,
  BicepsFlexed,
  Bell,
  Beer,
  Bird,
  Bold,
  BookOpen,
  BookOpenText,
  Camera,
  Calendar,
  CalendarPlus,
  Cannabis,
  CassetteTape,
  Cat,
  ChartCandlestick,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleSmall,
  CircleX,
  Cigarette,
  Clipboard,
  Clock,
  Coffee,
  Code,
  CodeXml,
  Coins,
  Copy,
  Cpu,
  CreditCard,
  DollarSign,
  Dog,
  Dumbbell,
  Ellipsis,
  Eye,
  File,
  FileText,
  Film,
  Fish,
  Folder,
  FolderCode,
  FolderOpen,
  FolderPlus,
  Frown,
  GlassWater,
  Globe,
  Hamburger,
  HardDrive,
  Heart,
  HandCoins,
  House,
  Hospital,
  Inbox,
  Info,
  Italic,
  Laptop,
  LampDesk,
  Landmark,
  Leaf,
  Layers,
  Layers2,
  LayoutDashboard,
  LibraryBig,
  Lightbulb,
  LightbulbOff,
  ListFilterPlus,
  LoaderCircle,
  LogOut,
  type LucideIconData,
  Mail,
  Minus,
  Monitor,
  Martini,
  Moon,
  MountainSnow,
  MoveRight,
  Music4,
  Palette,
  Pencil,
  PanelLeft,
  PiggyBank,
  Pill,
  Plus,
  Pizza,
  Popcorn,
  Puzzle,
  ReceiptText,
  Salad,
  Save,
  Scale,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Smile,
  Square,
  SquareLibrary,
  Star,
  Store,
  Sun,
  SunMoon,
  Tablet,
  Tag,
  Tags,
  Terminal,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignStart,
  Trash2,
  TreePalm,
  TriangleAlert,
  Underline,
  User,
  UserPlus,
  Users,
  Utensils,
  Vault,
  Wallet,
  X,
  Zap,
  Gamepad2,
  Gift,
  Glasses,
  GraduationCap,
  School,
  Shirt,
} from 'lucide-angular';

const DarkMode: LucideIconData = [
  ['path', { d: 'M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0' }],
  ['path', { d: 'M12 3l0 18' }],
  ['path', { d: 'M12 9l4.65 -4.65' }],
  ['path', { d: 'M12 14.3l7.37 -7.37' }],
  ['path', { d: 'M12 19.6l8.85 -8.85' }],
];

export const ZARD_ICONS = {
  house: House,
  settings: Settings,
  user: User,
  search: Search,
  bell: Bell,
  mail: Mail,
  calendar: Calendar,
  'log-out': LogOut,
  'panel-left': PanelLeft,
  bold: Bold,
  inbox: Inbox,
  italic: Italic,
  underline: Underline,
  'text-align-center': TextAlignCenter,
  'text-align-end': TextAlignEnd,
  'text-align-start': TextAlignStart,
  check: Check,
  x: X,
  info: Info,
  'triangle-alert': TriangleAlert,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'circle-dollar-sign': CircleDollarSign,
  'circle-small': CircleSmall,
  ban: Ban,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'move-right': MoveRight,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  file: File,
  'file-text': FileText,
  'layout-dashboard': LayoutDashboard,
  'loader-circle': LoaderCircle,
  save: Save,
  copy: Copy,
  eye: Eye,
  ellipsis: Ellipsis,
  terminal: Terminal,
  clipboard: Clipboard,
  moon: Moon,
  sun: Sun,
  lightbulb: Lightbulb,
  'lightbulb-off': LightbulbOff,
  palette: Palette,
  pencil: Pencil,
  sparkles: Sparkles,
  heart: Heart,
  star: Star,
  zap: Zap,
  popcorn: Popcorn,
  shield: Shield,
  puzzle: Puzzle,
  layers: Layers,
  'layers-2': Layers2,
  'square-library': SquareLibrary,
  code: Code,
  'code-xml': CodeXml,
  'book-open': BookOpen,
  'book-open-text': BookOpenText,
  users: Users,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  'badge-check': BadgeCheck,
  'folder-code': FolderCode,
  plus: Plus,
  minus: Minus,
  'arrow-left': ArrowLeft,
  archive: Archive,
  clock: Clock,
  'calendar-plus': CalendarPlus,
  'list-filter-plus': ListFilterPlus,
  trash: Trash2,
  tag: Tag,
  'sun-moon': SunMoon,
  'dark-mode': DarkMode,
  square: Square,
  'dollar-sign': DollarSign,
  'user-plus': UserPlus,
  'credit-card': CreditCard,
  activity: Activity,
  ambulance: Ambulance,
  armchair: Armchair,
  backpack: Backpack,
  baby: Baby,
  'banknote-arrow-down': BanknoteArrowDown,
  'banknote-arrow-up': BanknoteArrowUp,
  beer: Beer,
  'badge-euro': BadgeEuro,
  'badge-percent': BadgePercent,
  'biceps-flexed': BicepsFlexed,
  bird: Bird,
  camera: Camera,
  cannabis: Cannabis,
  'cassette-tape': CassetteTape,
  cat: Cat,
  cigarette: Cigarette,
  'chart-candlesticks': ChartCandlestick,
  coins: Coins,
  coffee: Coffee,
  cpu: Cpu,
  dog: Dog,
  'hand-coins': HandCoins,
  scale: Scale,
  school: School,
  shirt: Shirt,
  smile: Smile,
  dumbbell: Dumbbell,
  film: Film,
  fish: Fish,
  frown: Frown,
  gift: Gift,
  'gamepad-2': Gamepad2,
  glasses: Glasses,
  'graduation-cap': GraduationCap,
  'glass-water': GlassWater,
  globe: Globe,
  hamburger: Hamburger,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  hospital: Hospital,
  'lamp-desk': LampDesk,
  laptop: Laptop,
  landmark: Landmark,
  leaf: Leaf,
  'library-big': LibraryBig,
  martini: Martini,
  'mountain-snow': MountainSnow,
  'music-4': Music4,
  pizza: Pizza,
  'receipt-text': ReceiptText,
  salad: Salad,
  'shopping-cart': ShoppingCart,
  store: Store,
  tags: Tags,
  'hard-drive': HardDrive,
  'badge-info': BadgeInfo,
  pill: Pill,
  'piggy-bank': PiggyBank,
  'tree-palm': TreePalm,
  utensils: Utensils,
  vault: Vault,
  wallet: Wallet,
} as const satisfies Record<string, LucideIconData>;

export declare type ZardIcon = keyof typeof ZARD_ICONS | LucideIconData;
