const CHANNELS = Object.freeze({
  appMeta: Object.freeze({
    create: 'db:app-meta:create',
    get: 'db:app-meta:get',
    list: 'db:app-meta:list',
    update: 'db:app-meta:update',
    remove: 'db:app-meta:remove',
    upsert: 'db:app-meta:upsert',
  }),
  accountValuations: Object.freeze({
    create:               'db:account-valuations:create',
    get:                  'db:account-valuations:get',
    list:                 'db:account-valuations:list',
    update:               'db:account-valuations:update',
    remove:               'db:account-valuations:remove',
    getLatestByAccount:   'db:account-valuations:get-latest-by-account',
  }),
  accounts: Object.freeze({
    create: 'db:accounts:create',
    get: 'db:accounts:get',
    list: 'db:accounts:list',
    update: 'db:accounts:update',
    remove: 'db:accounts:remove',
  }),
  categories: Object.freeze({
    create: 'db:categories:create',
    get: 'db:categories:get',
    list: 'db:categories:list',
    update: 'db:categories:update',
    remove: 'db:categories:remove',
  }),
  budgets: Object.freeze({
    create: 'db:budgets:create',
    get: 'db:budgets:get',
    list: 'db:budgets:list',
    update: 'db:budgets:update',
    remove: 'db:budgets:remove',
  }),
  analytics: Object.freeze({
    availableYears: 'db:analytics:available-years',
    budgetVsExpensesByCategoryByYear: 'db:analytics:budget-vs-expenses-by-category-by-year',
    compareMonths: 'db:analytics:compare-months',
    expensesIncomesNetCashflowByMonth: 'db:analytics:expenses-incomes-net-cashflow-by-month',
    receivablesPayables: 'db:analytics:receivables-payables',
    netWorthByAccount: 'db:analytics:net-worth-by-account',
    expensesByCategoryByMonth: 'db:analytics:expenses-by-category-by-month',
    incomesByCategoryByMonth: 'db:analytics:incomes-by-category-by-month',
    moneyFlowSankeyByMonth: 'db:analytics:money-flow-sankey-by-month',
  }),
  planItems: Object.freeze({
    create: 'db:plan-items:create',
    get: 'db:plan-items:get',
    list: 'db:plan-items:list',
    update: 'db:plan-items:update',
    remove: 'db:plan-items:remove',
    run: 'db:plan-items:run',
    deletePlannedItems: 'db:plan-items:delete-planned-items',
  }),
  transactions: Object.freeze({
    create: 'db:transactions:create',
    createTransfer: 'db:transactions:create-transfer',
    updateTransfer: 'db:transactions:update-transfer',
    deleteTransfer: 'db:transactions:delete-transfer',
    get: 'db:transactions:get',
    listTransactions: 'db:transactions:list-transactions',
    listTransfers: 'db:transactions:list-transfers',
    update: 'db:transactions:update',
    remove: 'db:transactions:remove',
  }),
  backup: Object.freeze({
    getSettings: 'backup:getSettings',
    updateSettings: 'backup:updateSettings',
    getState: 'backup:getState',
    selectFolder: 'backup:selectFolder',
    list: 'backup:list',
    runNow: 'backup:runNow',
    remove: 'backup:remove',
    restore: 'backup:restore',
  }),
  dataExport: Object.freeze({
    exportXlsx: 'dataExport:exportXlsx',
    downloadImportTemplate: 'dataExport:downloadImportTemplate',
  }),
  importExcel: Object.freeze({
    selectFile: 'importExcel:selectFile',
    validate: 'importExcel:validate',
    commit: 'importExcel:commit',
  }),
  sync: Object.freeze({
    getSettings: 'sync:getSettings',
    updateSettings: 'sync:updateSettings',
    getState: 'sync:getState',
    selectFolder: 'sync:selectFolder',
    enable: 'sync:enable',
    repoStatus: 'sync:repoStatus',
    enableCreateRepo: 'sync:enableCreateRepo',
    enableAttachRepo: 'sync:enableAttachRepo',
    disable: 'sync:disable',
    syncNow: 'sync:syncNow',
    pullNow: 'sync:pullNow',
    pushNow: 'sync:pushNow',
    listSnapshots: 'sync:listSnapshots',
  }),
  reset: Object.freeze({
    clearFinancialData: 'db:reset:clear-financial-data',
    factoryReset: 'db:reset:factory-reset',
  }),
  update: Object.freeze({
    check: 'update:check',
    forceCheck: 'update:force-check',
    openRelease: 'update:open-release',
    ignoreVersion: 'update:ignore-version',
  }),
  window: Object.freeze({
    reload: 'window:reload',
  }),
});

module.exports = {
  CHANNELS,
};
